//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kandidaty_na_rabotu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч рег результ.
    /// </summary>
    // *** Start programmer edit section *** (ТЧРегРезульт CustomAttributes)

    // *** End programmer edit section *** (ТЧРегРезульт CustomAttributes)
    [AutoAltered()]
    [Caption("Регистрация результатов собеседования")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧРегРезультE", new string[] {
            "Сотрудники as \'ФИО сотрудника\'",
            "Сотрудники.ФИОСотр as \'ФИО сотрудника\'",
            "Сотрудники.Должность as \'Должность\'",
            "ОценкаКандид as \'Оценка кандидата\'",
            "ИтогСобесед as \'Итог собеседования\'",
            "КрКомИлиОбсРеш as \'Краткий комментарий или обоснованное решение\'"}, Hidden=new string[] {
            "Сотрудники.ФИОСотр"})]
    [MasterViewDefineAttribute("ТЧРегРезультE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОСотр")]
    public class ТЧРегРезульт : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Kandidaty_na_rabotu.ИтогСобесед fИтогСобесед;
        
        private int fОценкаКандид;
        
        private string fКрКомИлиОбсРеш;
        
        private IIS.Kandidaty_na_rabotu.Сотрудники fСотрудники;
        
        private IIS.Kandidaty_na_rabotu.РегРезульт fРегРезульт;
        
        // *** Start programmer edit section *** (ТЧРегРезульт CustomMembers)

        // *** End programmer edit section *** (ТЧРегРезульт CustomMembers)

        
        /// <summary>
        /// ИтогСобесед.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегРезульт.ИтогСобесед CustomAttributes)

        // *** End programmer edit section *** (ТЧРегРезульт.ИтогСобесед CustomAttributes)
        public virtual IIS.Kandidaty_na_rabotu.ИтогСобесед ИтогСобесед
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.ИтогСобесед Get start)

                // *** End programmer edit section *** (ТЧРегРезульт.ИтогСобесед Get start)
                IIS.Kandidaty_na_rabotu.ИтогСобесед result = this.fИтогСобесед;
                // *** Start programmer edit section *** (ТЧРегРезульт.ИтогСобесед Get end)

                // *** End programmer edit section *** (ТЧРегРезульт.ИтогСобесед Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.ИтогСобесед Set start)

                // *** End programmer edit section *** (ТЧРегРезульт.ИтогСобесед Set start)
                this.fИтогСобесед = value;
                // *** Start programmer edit section *** (ТЧРегРезульт.ИтогСобесед Set end)

                // *** End programmer edit section *** (ТЧРегРезульт.ИтогСобесед Set end)
            }
        }
        
        /// <summary>
        /// КрКомИлиОбсРеш.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш CustomAttributes)

        // *** End programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш CustomAttributes)
        [StrLen(255)]
        public virtual string КрКомИлиОбсРеш
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш Get start)

                // *** End programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш Get start)
                string result = this.fКрКомИлиОбсРеш;
                // *** Start programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш Get end)

                // *** End programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш Set start)

                // *** End programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш Set start)
                this.fКрКомИлиОбсРеш = value;
                // *** Start programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш Set end)

                // *** End programmer edit section *** (ТЧРегРезульт.КрКомИлиОбсРеш Set end)
            }
        }
        
        /// <summary>
        /// ОценкаКандид.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегРезульт.ОценкаКандид CustomAttributes)

        // *** End programmer edit section *** (ТЧРегРезульт.ОценкаКандид CustomAttributes)
        public virtual int ОценкаКандид
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.ОценкаКандид Get start)

                // *** End programmer edit section *** (ТЧРегРезульт.ОценкаКандид Get start)
                int result = this.fОценкаКандид;
                // *** Start programmer edit section *** (ТЧРегРезульт.ОценкаКандид Get end)

                // *** End programmer edit section *** (ТЧРегРезульт.ОценкаКандид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.ОценкаКандид Set start)

                // *** End programmer edit section *** (ТЧРегРезульт.ОценкаКандид Set start)
                this.fОценкаКандид = value;
                // *** Start programmer edit section *** (ТЧРегРезульт.ОценкаКандид Set end)

                // *** End programmer edit section *** (ТЧРегРезульт.ОценкаКандид Set end)
            }
        }
        
        /// <summary>
        /// Т ч рег результ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегРезульт.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ТЧРегРезульт.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Kandidaty_na_rabotu.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.Сотрудники Get start)

                // *** End programmer edit section *** (ТЧРегРезульт.Сотрудники Get start)
                IIS.Kandidaty_na_rabotu.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ТЧРегРезульт.Сотрудники Get end)

                // *** End programmer edit section *** (ТЧРегРезульт.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.Сотрудники Set start)

                // *** End programmer edit section *** (ТЧРегРезульт.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ТЧРегРезульт.Сотрудники Set end)

                // *** End programmer edit section *** (ТЧРегРезульт.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kandidaty_na_rabotu.РегРезульт.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегРезульт.РегРезульт CustomAttributes)

        // *** End programmer edit section *** (ТЧРегРезульт.РегРезульт CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РегРезульт"})]
        public virtual IIS.Kandidaty_na_rabotu.РегРезульт РегРезульт
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.РегРезульт Get start)

                // *** End programmer edit section *** (ТЧРегРезульт.РегРезульт Get start)
                IIS.Kandidaty_na_rabotu.РегРезульт result = this.fРегРезульт;
                // *** Start programmer edit section *** (ТЧРегРезульт.РегРезульт Get end)

                // *** End programmer edit section *** (ТЧРегРезульт.РегРезульт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегРезульт.РегРезульт Set start)

                // *** End programmer edit section *** (ТЧРегРезульт.РегРезульт Set start)
                this.fРегРезульт = value;
                // *** Start programmer edit section *** (ТЧРегРезульт.РегРезульт Set end)

                // *** End programmer edit section *** (ТЧРегРезульт.РегРезульт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧРегРезультE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧРегРезультE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧРегРезультE", typeof(IIS.Kandidaty_na_rabotu.ТЧРегРезульт));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧРегРезульт.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧРегРезульт CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧРегРезульт CustomAttributes)
    public class DetailArrayOfТЧРегРезульт : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kandidaty_na_rabotu.DetailArrayOfТЧРегРезульт members)

        // *** End programmer edit section *** (IIS.Kandidaty_na_rabotu.DetailArrayOfТЧРегРезульт members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧРегРезульт by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧРегРезульт.
        /// </summary>
        public DetailArrayOfТЧРегРезульт(IIS.Kandidaty_na_rabotu.РегРезульт fРегРезульт) : 
                base(typeof(ТЧРегРезульт), ((ICSSoft.STORMNET.DataObject)(fРегРезульт)))
        {
        }
        
        public IIS.Kandidaty_na_rabotu.ТЧРегРезульт this[int index]
        {
            get
            {
                return ((IIS.Kandidaty_na_rabotu.ТЧРегРезульт)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kandidaty_na_rabotu.ТЧРегРезульт dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
